import { writeFileSync } from "fs";

const jobs = [
  {
    title: "Graduate Software Engineer, Open Source and Linux",
    company: "Canonical",
    location: "Remote worldwide",
    url: "https://canonical.com/careers",
    description:
      "Work on open source Linux projects at Canonical. Python/Rust/Go/JS tech stack. Twice-yearly sprints. $2K/yr learning budget. For 2025/2026 grads.",
    salary: null,
    experience: "Entry Level / New Grad",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes:
      "Python/Rust/Go/JS; 2025/2026 grads; twice-yearly sprints; $2K/yr learning budget",
  },
  {
    title: "Junior Linux Kernel Engineer -- Ubuntu",
    company: "Canonical",
    location: "Remote worldwide",
    url: "https://canonical.com/careers",
    description:
      "Junior Linux Kernel Engineer working on Ubuntu. Python/Rust/Linux tech stack. Posted Aug 2026.",
    salary: null,
    experience: "Junior",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes: "Python/Rust/Linux; junior level; posted Aug 2026",
  },
  {
    title: "Junior Ubuntu Software Engineer",
    company: "Canonical",
    location: "Remote worldwide",
    url: "https://canonical.com/careers",
    description:
      "Junior Ubuntu Software Engineer. Python/Rust/C++/Flutter tech stack.",
    salary: null,
    experience: "Junior",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes: "Python/Rust/C++/Flutter; junior level",
  },
  {
    title: "Junior Rust Backend Engineer (Fleet Optimization)",
    company: "MOIA GmbH (Volkswagen)",
    location: "Berlin/Hamburg (hybrid)",
    url: "https://job-boards.eu.greenhouse.io/moia/jobs/4778042101",
    description:
      "Junior Rust Backend Engineer working on fleet optimization for MOIA, Volkswagen's mobility subsidiary. Rust/AWS/gRPC/K8s tech stack. 30 vacation days. Explicitly mentors early-career engineers.",
    salary: null,
    experience: "Junior",
    visa: "Yes -- visa + relocation",
    type: "hybrid",
    country: "Germany",
    notes:
      "Rust/AWS/gRPC/K8s; 30 vacation days; explicitly mentors early-career engineers",
  },
  {
    title: "Graduate Junior Software Engineer -- Backend",
    company: "Elwood Technologies",
    location: "Remote (London HQ)",
    url: "https://web3.career/graduate-junior-software-engineer-backend-elwoodtechnologies/151199",
    description:
      "Graduate/Junior Software Engineer - Backend at Elwood Technologies. FCA-regulated digital asset trading platform seeking graduates for backend engineering team. Rotations across internal teams working on Backend and Market Connectivity. Responsibilities include developing software, building features, working with Quants/Product/Algo teams, contributing to full software development lifecycle. STEM degree required, 6-18 months experience preferred, programming in C#, C++, Java, Python, Golang, or Rust.",
    salary: "£50,000",
    experience: "Junior/Graduate (6-18 months experience)",
    visa: "Check during application",
    type: "remote",
    country: "UK",
    notes:
      "C#/C++/Java/Python/Go/Rust; $50K; FCA-regulated FinTech; internship experience accepted",
  },
  {
    title: "Founding Software Engineer",
    company: "resnova",
    location: "Remote (India/Vietnam)",
    url: "https://wellfound.com/jobs/4492811-founding-software-engineer",
    description:
      "Founding Software Engineer at resnova building Conseleo, an AI-powered governance platform. Work directly with CTO to build product from ground up. Full-stack role spanning frontend, backend, infrastructure, AI integration, distributed systems, databases, and deployment.",
    salary: "USD 600-1,000 per month",
    experience: "1+ year",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes:
      "USD 600--1,000/mo; Rust nice-to-have; full-stack with AI/ML; Insurance RegTech startup",
  },
  {
    title: "Backend Rust Developer",
    company: "Proofoftrust",
    location: "Remote worldwide",
    url: "https://wellfound.com/jobs/4335792-backend-rust-developer",
    description:
      "Backend Rust Developer at Proofoftrust, an early-stage web3 professional networking startup. Seeking talented developers for a pre-launch platform. Fully remote with flexible working arrangements.",
    salary: "$60k-$70k + 0.0%-0.1% equity",
    experience: "2+ years",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes: "$60K--70K + equity; Rust; Web3 startup; Netherlands-based",
  },
  {
    title: "Fullstack React.js and Rust Developer",
    company: "Proofoftrust",
    location: "Remote worldwide",
    url: "https://wellfound.com/jobs/4521001-fullstack-react-js-and-rust-developer-clone",
    description:
      "Fullstack react.js and rust developer at Proofoftrust, an early-stage web3 professional networking startup. Seeking developers for a pre-launch platform.",
    salary: "$60k-$70k + 0.0%-0.1% equity",
    experience: "2+ years",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes: "$60K--70K + equity; React + Rust; perfect stack match",
  },
  {
    title: "Rust Developer",
    company: "Surya Financial Technologies",
    location: "Bangalore (hybrid remote)",
    url: null,
    description:
      "Rust Developer at India-based fintech company. Listed on RustJobs.dev.",
    salary: null,
    experience: "Entry Level",
    visa: "India-based",
    type: "hybrid",
    country: "India",
    notes: "India-based fintech; RustJobs.dev listing",
  },
  {
    title: "Rust Engineer",
    company: "Arionkoder",
    location: "Remote worldwide",
    url: "https://remotive.com/remote/jobs/software-development/rust-engineer-5379422",
    description:
      "Full-time Rust Engineer position. Mid-level but strong Rust portfolio may compensate.",
    salary: null,
    experience: "Mid-level",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes: "Full-time; mid-level but strong Rust portfolio may compensate",
  },
  {
    title: "Junior Developer",
    company: "Naylor LLC",
    location: "Remote (US)",
    url: "https://www.indeed.com/rc/clk?jk=16de5bcb795d6fc7",
    description:
      "Junior Developer position at Naylor LLC. Vue.js/React/Node.js tech stack. 0-2 years experience required. Health insurance + PTO benefits.",
    salary: null,
    experience: "0-2 years",
    visa: "Not specified",
    type: "remote",
    country: "USA",
    notes: "Vue.js/React/Node.js; 0--2 yrs; health insurance + PTO",
  },
  {
    title: "Agentic AI Engineer (Junior)",
    company: "Aline",
    location: "Remote (US)",
    url: "https://www.indeed.com/rc/clk?jk=731dfd555cf56cb1",
    description:
      "Junior Agentic AI Engineer position. React/TypeScript tech stack. Explicitly welcomes recent grads.",
    salary: "$65K--80K",
    experience: "Junior / New Grad",
    visa: "Not specified",
    type: "remote",
    country: "USA",
    notes: "$65K--80K; React/TypeScript; explicitly welcomes recent grads",
  },
  {
    title: "Entry-Level Frontend Engineer",
    company: "Robusta (Octopus by RTG)",
    location: "Remote (India)",
    url: "https://in.indeed.com/rc/clk?jk=183a0f7cbd1aff70",
    description:
      "Entry-Level Frontend Engineer. 9-month contract position. React tech stack. 4.7/5 employer rating.",
    salary: null,
    experience: "Entry Level",
    visa: "India-based",
    type: "remote",
    country: "India",
    notes: "9-month contract; React; 4.7/5 employer rating",
  },
  {
    title: "Junior Fullstack + AI Developer",
    company: "Cav",
    location: "Remote (US)",
    url: "https://www.indeed.com/rc/clk?jk=0fd6ac6605330e2d",
    description:
      "Junior Fullstack + AI Developer. Bootcamp graduates encouraged. React/TypeScript tech stack. Compliance automation focus.",
    salary: null,
    experience: "Junior",
    visa: "Not specified",
    type: "remote",
    country: "USA",
    notes:
      "Bootcamp graduates encouraged; React/TypeScript; compliance automation",
  },
  {
    title: "React Developer (Junior Level)",
    company: "Mercor",
    location: "Remote worldwide",
    url: "https://jooble.org/jdp/-7357085124557348089",
    description:
      "Junior Level React Developer. Contract position, 20 hrs/wk. Building React applications.",
    salary: "$50--80/hr",
    experience: "Junior",
    visa: "N/A (remote contract)",
    type: "remote",
    country: "Remote",
    notes: "$50--80/hr; contract 20 hrs/wk; React applications",
  },
  {
    title: "Fresh Graduate / Junior Fullstack Engineer",
    company: "Wizdaa",
    location: "Remote (EST/PST timezone)",
    url: "https://remotive.com/remote/jobs/software-development/fresh-graduate-junior-fullstack-engineer-4439676",
    description:
      "Fresh Graduate / Junior Fullstack Engineer. TypeScript/React/NestJS/GraphQL/Postgres stack. USD paid. Fresh grads explicitly welcome.",
    salary: null,
    experience: "Fresh Graduate / Junior",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes:
      "TypeScript/React/NestJS/GraphQL/Postgres; USD paid; fresh grads explicitly welcome",
  },
  {
    title: "Junior Developer",
    company: "Catch Creation LLC",
    location: "Remote (France timezone)",
    url: "https://remotive.com/remote/jobs/software-development/junior-developer-3592506",
    description:
      "Junior Developer. 0-2 years experience. NestJS/Next.js/TypeScript/Prisma/Tailwind stack.",
    salary: null,
    experience: "0-2 years",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes: "0--2 yrs; NestJS/Next.js/TypeScript/Prisma/Tailwind",
  },
  {
    title: "Founding Full-Stack Engineer (Junior-Mid)",
    company: "Notova",
    location: "Remote (PST overlap)",
    url: "https://www.usaremotejobs.app/job/notova-full-stack-software-engineer-junior-mid",
    description:
      "Founding Full-Stack Engineer at Notova, an AI-powered academic workspace. Audit and refactor an AI-built codebase, ship new features alongside founder and product designer. Stack: React, TypeScript, Node/Express, PostgreSQL, Supabase, Railway, Stripe, multi-provider AI APIs. First engineering hire with path to Head of Engineering.",
    salary: "$2,000-$3,000/month + founding equity",
    experience: "Junior-Mid (1-2 years experience, recent CS grads welcome)",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes:
      "$2K--3K/mo + equity; React/TS/Node/PostgreSQL/Supabase/Stripe; pre-seed startup",
  },
  {
    title: "Junior Fullstack Developer",
    company: "Wysa",
    location: "Remote / Bangalore, India",
    url: "https://wellfound.com/jobs/4287586-junior-fullstack-developer",
    description:
      "Junior Fullstack Developer at Wysa, an AI-based digital companion for behavioral health. Design, build, and maintain frontend/backend components, integrate with REST APIs, work with MongoDB.",
    salary: "₹7L – ₹8L per year",
    experience: "Entry Level (1-2 years)",
    visa: "India-based",
    type: "remote",
    country: "India",
    notes:
      "Rs 7--8L/yr; JS/Node/React/MongoDB; AI mental health; $23.3M funding",
  },
  {
    title: "Junior Full-Stack Developer",
    company: "junbrain.com",
    location: "Remote",
    url: "https://junbrain.com/jobs/project/junior-full-stack-developer/6lRnk5l",
    description:
      "Junior Full-Stack Developer. Develop responsive front-end features with React/CSS, construct back-end services with Node.js/Express, integrate with SQL/NoSQL databases, participate in code reviews and Agile ceremonies.",
    salary: null,
    experience: "Junior (Bachelor's degree required)",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes: "React/Node/Express/PostgreSQL; CS degree required",
  },
  {
    title: "Junior JavaScript Developer (React/Node.js)",
    company: "junbrain.com",
    location: "Remote",
    url: "https://junbrain.com/jobs/project/junior-javascript-developer-reactnodejs/jlPe7o9",
    description:
      "Junior JavaScript Developer (React/Node.js). Develop/deploy UI components with React, integrate with RESTful APIs, participate in Agile/Scrum, optimize for speed/scalability, implement unit/integration tests.",
    salary: null,
    experience: "Junior (Bachelor's degree required)",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes: "React/Node/Express/Redux; TypeScript preferred",
  },
  {
    title: "Junior Full-Stack JavaScript Developer",
    company: "DevelopsToday",
    location: "Remote (Ukraine/Brazil/Colombia)",
    url: "https://jobs.develops.today/jobs/full-stack-javascript-developer",
    description:
      "Junior Full-Stack JavaScript Developer. Build React apps and Node.js (Nest.js, Apollo Server) APIs for healthcare, fintech, eCommerce startups.",
    salary: "Competitive salary in USD",
    experience: "Junior",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes:
      "JS/TS/React/Next.js/Nest.js/Apollo/PostgreSQL; USD salary; 15 days vacation",
  },
  {
    title: "Junior Full-Stack Engineer",
    company: "FirmPilot",
    location: "Remote (USA only)",
    url: "https://remotive.com/remote/jobs/software-development/junior-full-stack-engineer-4679207",
    description:
      "Junior Full-Stack Engineer. $65K--80K salary. 1-2 years experience. JS/TS/React/Next.js/Node/AWS stack. AI marketing company.",
    salary: "$65K--80K",
    experience: "1-2 years",
    visa: "USA work authorization",
    type: "remote",
    country: "USA",
    notes: "$65K--80K; 1--2 yrs; JS/TS/React/Next.js/Node/AWS; AI marketing",
  },
  {
    title: "Software Developer",
    company: "Naksh Jewels",
    location: "WFH (India)",
    url: "https://internshala.com/fresher-jobs/full-stack-development-jobs/work-from-home/",
    description:
      "Software Developer. Rs 2--2.5L/yr salary. No experience required. Node/React/MySQL stack.",
    salary: "Rs 2--2.5L/yr",
    experience: "No experience required",
    visa: "India-based",
    type: "remote",
    country: "India",
    notes: "Rs 2--2.5L/yr; no exp required; Node/React/MySQL",
  },
  {
    title: "Software Engineer",
    company: "SharePal",
    location: "WFH (India)",
    url: "https://internshala.com/fresher-jobs/full-stack-development-jobs/work-from-home/",
    description:
      "Software Engineer. Rs 4--6L/yr salary. No experience required. Full stack role.",
    salary: "Rs 4--6L/yr",
    experience: "No experience required",
    visa: "India-based",
    type: "remote",
    country: "India",
    notes: "Rs 4--6L/yr; no exp required; full stack",
  },
  {
    title: "Software Engineer, New Grad (Fullstack)",
    company: "Micro1",
    location: "Remote worldwide",
    url: "https://micro1.ai/careers",
    description:
      "Software Engineer, New Grad (Fullstack). $110K--150K + equity. Full-stack role. CS degree required.",
    salary: "$110K--150K + equity",
    experience: "New Grad",
    visa: "Not specified",
    type: "remote",
    country: "Remote",
    notes: "$110K--150K + equity; full-stack; CS degree required",
  },
  {
    title: "Junior Software Engineer",
    company: "Docplanner",
    location: "Remote worldwide",
    url: "https://remotive.com/remote/jobs/software-development/junior-software-engineer-4168163",
    description:
      "Junior Software Engineer at Docplanner. Healthcare tech company. Share options after 6 months. 20--26 days PTO.",
    salary: null,
    experience: "Junior",
    visa: "N/A (fully remote)",
    type: "remote",
    country: "Remote",
    notes: "Healthcare tech; share options after 6 months; 20--26 days PTO",
  },
  {
    title: "Junior Software Engineer",
    company: "MixRank (YC S11)",
    location: "Remote (20+ countries)",
    url: "https://www.ycombinator.com/companies/mixrank/jobs/Fnwsojk-junior-software-engineer-remote-global-full-time",
    description:
      "Junior Software Engineer at MixRank processing petabytes of data monthly. Full-remote team of 65+ across 20+ countries. Work on web applications, data mining, ML/data science, ETL, database scaling, infrastructure, devops.",
    salary: "$12,000 - $24,000",
    experience: "Any (new grads ok)",
    visa: "Global remote",
    type: "remote",
    country: "Remote",
    notes:
      "$12K--24K/yr region-adjusted; Python/Rust/SQL/TS; employee-owned; 65+ FT",
  },
  {
    title: "Graduate Software Engineer",
    company: "Bending Spoons",
    location: "Remote (primarily EU/US)",
    url: null,
    description:
      "Graduate Software Engineer at Bending Spoons. AI tools; unlimited training; 50% tax cut if relocating to Italy. Relocation package provided.",
    salary: null,
    experience: "Graduate",
    visa: "Relocation package",
    type: "remote",
    country: "Remote",
    notes: "AI tools; unlimited training; 50% tax cut if relocating to Italy",
  },
  {
    title: "Software Engineer, New Grad (Full Stack)",
    company: "Cherry Technologies",
    location: "Remote (Turkey-based)",
    url: "https://remoteyeah.com/jobs/remote-software-engineer-new-grad-cherry-technologies-inc",
    description:
      "Software Engineer, New Grad (Full Stack). $2,750/mo + health + stock options. Node/React/Vue stack. Must speak Turkish.",
    salary: "$2,750/mo + health + stock options",
    experience: "New Grad",
    visa: "Turkey contract",
    type: "remote",
    country: "Turkey",
    notes:
      "$2,750/mo + health + stock options; Node/React/Vue; must speak Turkish",
  },
  {
    title: "Graduate Software Engineer",
    company: "LetsGetChecked",
    location: "Remote (US)",
    url: "https://builtin.com/job/graduate-software-engineer/8975681",
    description:
      "Graduate Software Engineer at LetsGetChecked (healthcare/telehealth). Analyze logs/data, triage issues, aid feature development, maintain documentation.",
    salary: "$76,000 - $95,000 Annually",
    experience: "Entry level",
    visa: "US work authorization",
    type: "remote",
    country: "USA",
    notes: "$76K--95K; healthcare tech; Python/C#/JS; cloud platforms",
  },
  {
    title: "Graduate Software Engineer -- 2026 Grads Welcome",
    company: "S Merrick LTD",
    location: "Remote (UK only)",
    url: "https://www.totaljobs.com/job/graduate-software-engineer-2026-graduates-welcome-remote-uk/s-merrick-ltd-job107642245",
    description:
      "Graduate Software Engineer. £25K + bonus. C#/PHP/SQL/Azure stack. Financial services company.",
    salary: "£25K + bonus",
    experience: "Graduate / 2026 Grads",
    visa: "UK right to work",
    type: "remote",
    country: "UK",
    notes: "£25K + bonus; C#/PHP/SQL/Azure; financial services",
  },
  {
    title: "Entry-Level Software Engineer",
    company: "Getcrate (Crate Platforms LLC)",
    location: "Remote (PST timezone)",
    url: "https://builtin.com/job/software-engineer/9938392",
    description:
      "Entry-Level Software Engineer at Getcrate (social media/AI platform). Develop, test, deploy features; code reviews; troubleshooting; optimization.",
    salary: "$129,000 - $155,000 Annually",
    experience: "Entry level",
    visa: "US work authorization",
    type: "remote",
    country: "USA",
    notes: "$129K--155K; ad-tech; Python/JS/Java/C++; React/Angular/Node",
  },
  {
    title: "Entry-Level Software Engineer",
    company: "Tilt",
    location: "Remote (US)",
    url: "https://remoteotter.com/company/tilt/jobs/remote-entry-level-software-engineer_0f9a264a-7b39-4c6f-a26a-aebafc2f64fc",
    description:
      "Entry-Level Software Engineer at Tilt (leave management platform). Maintain production code, collaborate with senior engineers, learn core engineering concepts.",
    salary: "$100,000 - $110,000 per year",
    experience: "Entry level (completed degree or coding bootcamp)",
    visa: "US work authorization",
    type: "remote",
    country: "USA",
    notes: "$100K--110K; HR/benefits tech; Python/Django + TS/React",
  },
  {
    title: "Software Engineer -- New Grad 2026",
    company: "Arcline",
    location: "San Francisco (Hybrid) / Remote OK",
    url: "https://www.eduarcline.us/careers/software-engineer-new-grad",
    description:
      "Software Engineer -- New Grad 2026 at Arcline (AI data tools for K-12 education). Own product surfaces end-to-end: scope, design, build, ship, iterate.",
    salary: "$140,000 - $190,000 + equity",
    experience: "New Grad (graduating by Summer 2026)",
    visa: "Not specified",
    type: "hybrid",
    country: "USA",
    notes:
      "$140K--190K + equity; TS/Python/SQL; climate tech; start Summer/Fall 2026",
  },
  {
    title: "Developer Advocate Contractor (Open Source)",
    company: "AnChain.AI",
    location: "Fully remote (flexible hours)",
    url: "https://anchain.ai/careers",
    description:
      "Developer Advocate Contractor (Open Source). 10-20 hrs/wk; 3-6 month contract. Create demo videos/tutorials in Python/TS/Go. GitHub portfolio required.",
    salary: null,
    experience: "Entry Level",
    visa: "N/A (remote)",
    type: "remote",
    country: "Remote",
    notes:
      "10--20 hrs/wk; 3--6 month contract; demo videos/tutorials in Python/TS/Go; GitHub portfolio required",
  },
  {
    title: "Developer Advocate / Community Engineer",
    company: "Vueform",
    location: "Fully remote (async)",
    url: null,
    description:
      "Developer Advocate / Community Engineer. Part-time 10 hrs/wk. Triage GitHub issues, Discord support, fix small bugs. Early in your journey welcome.",
    salary: null,
    experience: "Entry Level",
    visa: "N/A (remote worldwide)",
    type: "remote",
    country: "Remote",
    notes:
      "Part-time 10 hrs/wk; triage GitHub issues; Discord; fix small bugs; early in your journey welcome",
  },
  {
    title: "Developer Relations Engineer (Junior)",
    company: "Vyper (Ethereum)",
    location: "Fully remote",
    url: null,
    description:
      "Developer Relations Engineer (Junior). 4-6 month contract. Create examples/tutorials. Python ideal. Junior role but not small.",
    salary: null,
    experience: "Junior",
    visa: "N/A (remote)",
    type: "remote",
    country: "Remote",
    notes:
      "4--6 month contract; create examples/tutorials; Python ideal; junior role but not small",
  },
  {
    title: "Developer Advocate Intern",
    company: "Weaviate",
    location: "Fully remote (global)",
    url: "https://joblaze.com/jobs/developer-advocate-intern-7270aa",
    description:
      "Developer Advocate Intern at Weaviate (AI vector database startup). Create engaging content simplifying AI concepts, blog posts, social media visuals, example projects.",
    salary: null,
    experience: "Intern (university student)",
    visa: "N/A (remote)",
    type: "remote",
    country: "Remote",
    notes:
      "Must be enrolled in university; AI/vector DB; conference + education budget",
  },
  {
    title: "Documentation Engineer",
    company: "Chainlink Labs",
    location: "Remote (India/Colombia)",
    url: "https://remotive.com/remote/jobs/writing/documentation-engineer-3758097",
    description:
      "Documentation Engineer. Solidity/JS/TS/Markdown/Git skills. Nice-to-have: Rust/Go. Posted 2 days ago.",
    salary: null,
    experience: "Entry Level",
    visa: "India-eligible",
    type: "remote",
    country: "Remote",
    notes:
      "Solidity/JS/TS/Markdown/Git; nice-to-have: Rust/Go; posted 2 days ago",
  },
  {
    title: "Developer Relations Engineer (Contract-to-Hire)",
    company: "Coder",
    location: "Remote (US-based company)",
    url: "https://www.linkedin.com/jobs/view/developer-relations-engineer-at-coder-4416870093",
    description:
      "Developer Relations Engineer at Coder (AI/remote development platform). Curate template registry, improve community docs/guides, engage in Discord/GitHub.",
    salary: null,
    experience: "Entry level",
    visa: "Check during application",
    type: "remote",
    country: "USA",
    notes:
      "Open-source remote dev platform; template registry; KubeCon/FOSDEM talks; 103 applicants",
  },
  {
    title: "Graduate Software Engineer (2026)",
    company: "IMC Trading",
    location: "Amsterdam",
    url: "https://career.now/r/j/en4yv.UqBfobOY",
    description:
      "Graduate Software Engineer at IMC in Amsterdam. Five-week Global Trainee Programme followed by work on execution or strategy teams building advanced algorithms, trading platforms, and software stack.",
    salary: null,
    experience: "Entry-level / Graduate (final year of CS/SE degree)",
    visa: "Yes -- HSM via IND",
    type: "onsite",
    country: "Netherlands",
    notes:
      "5-week Global Trainee; C++/Java; Feb or Aug 2026 start; posted 1d ago",
  },
  {
    title: "Graduate Software Engineer",
    company: "Adyen",
    location: "Amsterdam",
    url: "https://careers.adyen.com/vacancies",
    description:
      "Graduate Software Engineer at Adyen. Java platform; PostgreSQL; low-latency API. 8+ live early-career roles.",
    salary: null,
    experience: "Graduate",
    visa: "Yes -- HSM + relocation",
    type: "onsite",
    country: "Netherlands",
    notes:
      "Java platform; PostgreSQL; low-latency API; 8+ live early-career roles",
  },
  {
    title: "Compass SE Graduate",
    company: "Booking.com",
    location: "Amsterdam",
    url: "https://careers.booking.com/",
    description:
      "Compass SE Graduate at Booking.com. 12-month grad program. SWE or Data Science tracks. Sep 2026 intake.",
    salary: null,
    experience: "Graduate",
    visa: "Yes -- HSM",
    type: "onsite",
    country: "Netherlands",
    notes:
      "12-month grad program; SWE or Data Science; Sep 2026 intake; 150+ nationalities",
  },
  {
    title: "Junior Kubernetes Platform Developer",
    company: "ING Bank",
    location: "Amsterdam",
    url: "https://www.ing.com/careers",
    description:
      "Junior Kubernetes Platform Developer at ING Bank. EUR 45K--65K salary. 25-28 vacation days + 13th month + 8% holiday pay.",
    salary: "EUR 45K--65K",
    experience: "Junior",
    visa: "Yes -- HSM",
    type: "hybrid",
    country: "Netherlands",
    notes:
      "EUR 45K--65K; 25--28 vacation days + 13th month + 8% holiday pay; hybrid",
  },
  {
    title: "Software Engineer II (Networking)",
    company: "Elastic",
    location: "Amsterdam (remote option)",
    url: "https://www.elastic.co/careers",
    description:
      "Software Engineer II (Networking) at Elastic. Elasticsearch/OpenSearch; search/observability/security.",
    salary: null,
    experience: "Mid-level",
    visa: "Yes -- HSM",
    type: "hybrid",
    country: "Netherlands",
    notes:
      "Elasticsearch/OpenSearch; search/observability/security; multiple NL roles",
  },
  {
    title: "Junior Rust Developer (Security for AI)",
    company: "1Password",
    location: "Remote (Netherlands-based)",
    url: "https://jobs.ashbyhq.com/1password/25a2955f-afb4-4936-b243-58d6dc26438b",
    description:
      "Junior Rust Developer (Security for AI) at 1Password. Security for AI focus. 1+ yr Rust (internship counts).",
    salary: null,
    experience: "Junior (1+ yr Rust, internship counts)",
    visa: "HSM likely (Dutch entity)",
    type: "remote",
    country: "Netherlands",
    notes: "Security for AI; 1+ yr Rust (internship counts); Go/TS bonus; RSUs",
  },
  {
    title: "Frontend Software Engineer",
    company: "QuantCo",
    location: "Remote or Hybrid (Turkey eligible)",
    url: "https://builtin.com/jobs/mena/turkey/dev-engineering/search/software-engineer",
    description:
      "Frontend Software Engineer at QuantCo. React/TS/Python stack. ML solutions UI. Berlin-based company.",
    salary: null,
    experience: "Entry Level",
    visa: "N/A (remote-first)",
    type: "remote",
    country: "Remote",
    notes: "React/TS/Python; ML solutions UI; Berlin-based, 100+ employees",
  },
  {
    title: "Graduate Software Engineer",
    company: "Cobblestone Energy",
    location: "Dubai (on-site)",
    url: "https://job-boards.greenhouse.io/cobblestoneenergy/jobs/7772324003",
    description:
      "Graduate Software Engineer at Cobblestone Energy in Dubai. $65K/yr + bonus. 0% tax. Python/JS stack.",
    salary: "$65K/yr + bonus",
    experience: "Graduate",
    visa: "Yes -- visa + relocation",
    type: "onsite",
    country: "UAE",
    notes:
      "$65K/yr + bonus; 0% tax; Python/JS; AI tools valued; expires Sep 11, 2026",
  },
  {
    title: "Frontend SWE Graduate (Corporate Service System) -- 2026",
    company: "ByteDance (TikTok)",
    location: "Dubai",
    url: "https://jobs.bytedance.com/en/position/74976451",
    description:
      "Frontend SWE Graduate at ByteDance/TikTok. Perfect React/TS match. BS/MS 2026 graduates.",
    salary: null,
    experience: "New Grad (BS/MS 2026)",
    visa: "Yes -- MNC visa",
    type: "onsite",
    country: "UAE",
    notes: "Perfect React/TS match; BS/MS 2026; rolling basis; max 2 positions",
  },
  {
    title: "SWE Graduate (Corporate Information System) -- 2026",
    company: "ByteDance (TikTok)",
    location: "Dubai",
    url: "https://jobs.bytedance.com/en/position/74976451",
    description:
      "SWE Graduate at ByteDance/TikTok. Java/Go/C++/Python stack. DSA + system design focus.",
    salary: null,
    experience: "New Grad (BS/MS 2026)",
    visa: "Yes -- MNC visa",
    type: "onsite",
    country: "UAE",
    notes: "Java/Go/C++/Python; DSA + system design; rolling",
  },
  {
    title: "Graduate Software Engineer -- Java (2027 Programme)",
    company: "Revolut",
    location: "Dubai (hybrid 3 days/wk)",
    url: "https://ae.jobiglo.com/",
    description:
      "Graduate Software Engineer -- Java (2027 Programme) at Revolut. 12-month structured training.",
    salary: null,
    experience: "Graduate",
    visa: "Yes -- visa + travel + 1st month accommodation",
    type: "hybrid",
    country: "UAE",
    notes: "12-month structured training; published hours ago; fintech",
  },
  {
    title: "Technology Associate (1-Year Graduate Program)",
    company: "Emirates Group",
    location: "Dubai",
    url: "https://www.emiratesgroupcareers.com/search-and-apply/463723",
    description:
      "Technology Associate at Emirates Group. AI/cloud/cybersecurity/SWE focus. CGPA 3.0+ required.",
    salary: null,
    experience: "Graduate (CGPA 3.0+)",
    visa: "Yes -- visa + tax-free",
    type: "onsite",
    country: "UAE",
    notes:
      "AI/cloud/cybersecurity/SWE; CGPA 3.0+; flight/hotel discounts worldwide",
  },
  {
    title: "Graduate Associate Software Engineer (2-Year Program)",
    company: "Emirates Group",
    location: "Dubai",
    url: "https://www.emiratesgroupcareers.com/search-and-apply/463723",
    description:
      "Graduate Associate Software Engineer at Emirates Group. CS/IT/SE degree required.",
    salary: null,
    experience: "Graduate (CS/IT/SE degree)",
    visa: "Yes -- visa + tax-free",
    type: "onsite",
    country: "UAE",
    notes: "CS/IT/SE degree; software engineering focused",
  },
  {
    title: "AI Engineer",
    company: "BroadPeak Investment Group",
    location: "Remote (on-site Dubai from Sep 2026)",
    url: "https://ae.linkedin.com/jobs/view/ai-engineer-broadpeak-uae-at-broadpeak-investment-group-4443220373",
    description:
      "AI Engineer at BroadPeak Investment Group. Build and ship AI into software. Hands-on with generative AI platforms.",
    salary: "Competitive salary (tax-free in UAE)",
    experience: "2-3 years hands-on AI/software implementation",
    visa: "Yes -- visa + relocation",
    type: "remote",
    country: "UAE",
    notes: "Early-career; Python/JS; AI tools (Cursor/Copilot); small team",
  },
  {
    title: "Commercial Graduate Scheme -- Junior Data Scientist",
    company: "Cobblestone Energy",
    location: "Dubai (on-site)",
    url: "https://job-boards.greenhouse.io/cobblestoneenergy4/jobs/7772319003",
    description:
      "Junior Data Scientist at Cobblestone Energy. Data preparation, forecasting/modeling, AI-accelerated workflows using LLMs.",
    salary: "USD 65,000 per annum + bonus",
    experience: "Entry-level / Graduate",
    visa: "Yes -- visa + relocation",
    type: "onsite",
    country: "UAE",
    notes: "$65K/yr + bonus; Python/SQL/Pandas; LLM integration a plus",
  },
  {
    title: "Junior Software Developer (Entry Level)",
    company: "Career.zycto",
    location: "Dubai (Barsha Heights)",
    url: "https://career.zycto.com/jobs/junior-software-developer-entry-level/",
    description:
      "Junior Software Developer at Career.zycto. Design, develop, test, deploy software applications.",
    salary: "AED 5,000 - 8,000 per month",
    experience: "Entry-level",
    visa: "Likely sponsor",
    type: "onsite",
    country: "UAE",
    notes: "AED 5K--8K/mo; Python/Java/C#/JS; mentorship; health insurance",
  },
  {
    title: "Junior Software Developer (Banking)",
    company: "TAWANTECH",
    location: "Riyadh (on-site)",
    url: "https://apply.workable.com/j/ED1D93453F/apply",
    description:
      "Junior Software Developer (Banking Systems) at TAWANTECH. Fresh graduates with CS degree.",
    salary: null,
    experience: "Entry-level / Fresh graduate",
    visa: "Contact employer",
    type: "onsite",
    country: "Saudi Arabia",
    notes: "Fresh grad or up to 1yr; Java/C#/Python/JS; fintech",
  },
  {
    title: "Computing & IT Graduates Program",
    company: "Saudi Aramco",
    location: "Dhahran",
    url: "https://careers.aramco.com/saudi/job/Computing-and-IT-Graduates-%28less-than-three-years-of-work-experience%29/766636523/",
    description:
      "Computing & IT Graduates Program at Saudi Aramco. No prior experience required.",
    salary: null,
    experience: "No prior exp required",
    visa: "Yes -- Aramco sponsors",
    type: "onsite",
    country: "Saudi Arabia",
    notes: "No prior exp required; closes Dec 31, 2026",
  },
  {
    title: "Junior React Developer",
    company: "Tech Pipeline",
    location: "Saudi Arabia (fully remote)",
    url: "https://sa.linkedin.com/jobs/view/junior-react-developer-at-tech-pipeline-4444689931",
    description:
      "Junior React Developer. React/JS/HTML/CSS stack. Entry-level. Permanent position.",
    salary: null,
    experience: "Entry Level",
    visa: "Listed",
    type: "remote",
    country: "Saudi Arabia",
    notes: "React/JS/HTML/CSS; entry-level; permanent; posted Jul 26",
  },
  {
    title: "Junior React Developer",
    company: "Bavarian Capital",
    location: "Saudi Arabia (fully remote)",
    url: "https://jaabz.com/jobs/255059-junior-react-developer",
    description:
      "Build and maintain React components for internal dashboards providing real-time visibility into reconciliation and routing data.",
    salary: null,
    experience: "Entry level",
    visa: "Visa + relocation + remote",
    type: "remote",
    country: "Saudi Arabia",
    notes: "React components for financial dashboards; entry-level",
  },
  {
    title: "Junior AI Automation Developer",
    company: "Bavarian Capital",
    location: "Saudi Arabia (fully remote)",
    url: "https://jaabz.com/jobs/253027-junior-ai-automation-developer",
    description:
      "Build and maintain Python-based automation tools for capital management processes.",
    salary: null,
    experience: "Entry level",
    visa: "Visa + relocation + remote",
    type: "remote",
    country: "Saudi Arabia",
    notes: "Python/JS automation; capital management; entry-level",
  },
  {
    title: "Associate Software Developer (Fresh Grad Program)",
    company: "Black Pearl Consult",
    location: "Riyadh",
    url: "https://blackpearlconsult.zohorecruit.com/jobs/Black-Pearl/425537000072789720/Associate-Software-Developer-Fresh-Graduates-Program-",
    description:
      "Associate Software Developer. Any nationality. Arabic required. 2-month paid training.",
    salary: null,
    experience: "Fresh Graduate",
    visa: "Yes -- visa confirmed",
    type: "onsite",
    country: "Saudi Arabia",
    notes:
      "Any nationality; Arabic required; 2-month paid training; airport tech project",
  },
  {
    title: "Software Engineer (Early Career)",
    company: "GE Aerospace",
    location: "Doha (remote)",
    url: "https://qa.indeed.com/rc/clk?jk=253e99f8f244cfcc",
    description:
      "Software Engineer (Early Career) at GE Aerospace. 0-2 years experience. Python/C++/Go/Rust stack.",
    salary: null,
    experience: "0-2 years",
    visa: "Likely (MNC)",
    type: "remote",
    country: "Qatar",
    notes: "0--2 yrs; Python/C++/Go/Rust; cloud/AI focus",
  },
  {
    title: "Graduate Technology Trainee",
    company: "KARTY",
    location: "Doha (in-person)",
    url: "https://qa.indeed.com/rc/clk?jk=3f56af94314b5435",
    description:
      "Graduate Technology Trainee. QAR 2K/mo salary. 3-6 month contract. Fresh grads.",
    salary: "QAR 2K/mo",
    experience: "Fresh Graduate",
    visa: "Confirm during application",
    type: "onsite",
    country: "Qatar",
    notes: "QAR 2K/mo; 3--6 month contract; fresh grads; QCB-licensed fintech",
  },
  {
    title: "Solution Engineer Intern (Erada)",
    company: "Microsoft",
    location: "Doha",
    url: "https://qa.indeed.com/rc/clk?jk=287dc818a87df15c",
    description:
      "Solution Engineer Intern at Microsoft. Customer-facing role. Product expertise focus.",
    salary: null,
    experience: "Intern",
    visa: "Yes -- Microsoft sponsors",
    type: "onsite",
    country: "Qatar",
    notes: "Customer-facing; product expertise; posted 11 days ago",
  },
  {
    title: "AI Software Engineer -- Full Stack (Java)",
    company: "EPAM Systems",
    location: "Doha (on-site)",
    url: "https://qa.linkedin.com/jobs/view/ai-software-engineer-full-stack-developer-java-at-epam-systems-4446785509",
    description:
      "AI Software Engineer -- Full Stack (Java) at EPAM Systems. Focuses on enabling AI-assisted delivery.",
    salary: null,
    experience: "Mid-Senior level",
    visa: "Yes -- full benefits",
    type: "onsite",
    country: "Qatar",
    notes: "Java/Spring Boot/AI/LLM; 62K+ employees globally; 20 days vacation",
  },
  {
    title: "Junior Full Stack Developer",
    company: "Ainholding",
    location: "Doha",
    url: "https://qa.jooble.org/jdp/6889439013323090728",
    description:
      "Junior Full Stack Developer. Java/Swift stack. CI/CD (Jenkins/GitHub).",
    salary: null,
    experience: "Junior",
    visa: "Confirm during application",
    type: "onsite",
    country: "Qatar",
    notes: "Java/Swift; CI/CD (Jenkins/GitHub); posted Jul 9",
  },
  {
    title: "Junior Python Developer",
    company: "Mindstream",
    location: "Doha",
    url: "https://qa.indeed.com/rc/clk?jk=7df00c47132a87ea",
    description:
      "Junior Python Developer. Python/FastAPI stack. REST APIs. AI API integration.",
    salary: null,
    experience: "Junior",
    visa: "Confirm during application",
    type: "onsite",
    country: "Qatar",
    notes: "Python/FastAPI; REST APIs; AI API integration",
  },
  {
    title: "Software Engineer I (Entry-Level)",
    company: "Experian",
    location: "Cyberjaya (hybrid)",
    url: "https://jobs.smartrecruiters.com/Experian/744000142802189-software-engineer-i",
    description:
      "Software Engineer I at Experian. Java tech stacks. Design and implement automated tests. AI-assisted engineering tools.",
    salary: null,
    experience: "0-2 years",
    visa: "Likely -- MNC",
    type: "hybrid",
    country: "Malaysia",
    notes: "Java; AWS/Azure/GCP; CI/CD; 0 yrs exp; FTSE 100",
  },
  {
    title: "Junior AI Developer (12-Month Contract)",
    company: "Experian",
    location: "KL (hybrid)",
    url: "https://jobs.smartrecruiters.com/Experian/744000142562859-junior-ai-developer-12-months-contract-",
    description:
      "Junior AI Developer at Experian. Designing, building AI-powered features including chatbots, workflow automation.",
    salary: null,
    experience: "Junior (CS degree)",
    visa: "Likely -- MNC",
    type: "hybrid",
    country: "Malaysia",
    notes: "React/Next.js/Python/.Net/AI/ML; CS degree required",
  },
  {
    title: "Full Stack Developer (Junior)",
    company: "Avanade (Microsoft + Accenture JV)",
    location: "KL (hybrid)",
    url: "https://my.jobstreet.com/job/89731406",
    description:
      "Full Stack Developer at Avanade. .NET/Azure stack. Enterprise projects.",
    salary: "RM 4.5K--6K/mo",
    experience: "Junior",
    visa: "Highly likely -- MNC",
    type: "hybrid",
    country: "Malaysia",
    notes: "RM 4.5K--6K/mo; .NET/Azure; enterprise projects",
  },
  {
    title: "Software Engineer (Fresh Graduates Only)",
    company: "Motorola Solutions",
    location: "Penang (onsite)",
    url: "https://my.jobstreet.com/job/85916436",
    description:
      "Software Engineer at Motorola Solutions. Good programming skills required. Medical + cafeteria benefits.",
    salary: null,
    experience: "Fresh Graduate",
    visa: "Likely -- MNC",
    type: "onsite",
    country: "Malaysia",
    notes:
      "Good programming skills; medical + cafeteria; one of biggest Penang employers",
  },
  {
    title: "Junior Full-Stack Developer",
    company: "Coevolve",
    location: "Malaysia (remote/hybrid)",
    url: "https://www.coevolve.com/contact-us/join-our-team/junior-full-stack-developer-malaysia/",
    description:
      "Junior Full-Stack Developer at Coevolve. Next-gen networking. TS/React/Node stack.",
    salary: null,
    experience: "Junior",
    visa: "Highly likely -- international",
    type: "remote",
    country: "Malaysia",
    notes: "Next-gen networking; TS/React/Node; 80+ countries",
  },
  {
    title: "Full Stack Engineer (Fresh Graduate)",
    company: "Hitachi eBworx",
    location: "Petaling Jaya",
    url: "https://my.jobstreet.com/job/91136810",
    description:
      "Full Stack Engineer at Hitachi eBworx. Japanese multinational. Fresh grad focus.",
    salary: null,
    experience: "Fresh Graduate",
    visa: "Likely -- MNC",
    type: "onsite",
    country: "Malaysia",
    notes: "Japanese multinational; fresh grad focus",
  },
  {
    title: "Junior Developer (Ruby on Rails)",
    company: "Dynamite Games",
    location: "KL (hybrid)",
    url: "https://my.jobstreet.com/job/85253738",
    description:
      "Junior Developer (Ruby on Rails) at Dynamite Games. Fast-growing gaming company.",
    salary: "RM 5K--7K/mo",
    experience: "Junior",
    visa: "Likely -- Singapore company",
    type: "hybrid",
    country: "Malaysia",
    notes: "RM 5K--7K/mo; fast-growing gaming; expiring soon",
  },
  {
    title: "Junior Full Stack Developer",
    company: "Bifrost Intelligence",
    location: "Bangsar South, KL",
    url: "https://my.jobstreet.com/job/85685280",
    description:
      "Junior Full Stack Developer at Bifrost Intelligence. AI/fintech company.",
    salary: "RM 6K--8K/mo",
    experience: "Junior",
    visa: "Unclear",
    type: "onsite",
    country: "Malaysia",
    notes:
      "RM 6K--8K/mo; AI/fintech; code user-facing interfaces across countries",
  },
  {
    title: "Software Engineer (Fresh Graduate / Interns)",
    company: "VYKON Communications",
    location: "KL (hybrid)",
    url: "https://my.jobstreet.com/job/85994353",
    description:
      "Software Engineer at VYKON Communications. Fresh graduates and interns welcome.",
    salary: "MYR 3K--4.5K entry",
    experience: "Fresh Graduate / Intern",
    visa: "Unclear",
    type: "hybrid",
    country: "Malaysia",
    notes: "MYR 3K--4.5K entry; up to MYR 10K experienced; EPF 15.5%",
  },
  {
    title: "Junior Software Engineer",
    company: "PT Pinhome",
    location: "Jakarta Selatan (hybrid)",
    url: "https://www.pinhome.id/pages/career/",
    description:
      "Junior Software Engineer at PT Pinhome. Real estate tech company with $105.5M funding.",
    salary: null,
    experience: "Junior",
    visa: "Unlikely -- local startup",
    type: "hybrid",
    country: "Indonesia",
    notes: "$105.5M funding; 200--300 employees; real estate tech",
  },
  {
    title: "Full-Stack Software Engineer (Remote)",
    company: "Wexa AI (CognoDB)",
    location: "Remote (Indonesia-based)",
    url: "https://jaabz.com/jobs/260701-software-engineer-full-stack-web",
    description:
      "Full-Stack Software Engineer at Wexa AI. Build web applications and console features. React, JavaScript, HTML/CSS stack.",
    salary: null,
    experience: "0-15 years (Mid-Level)",
    visa: "N/A -- remote from home country",
    type: "remote",
    country: "Indonesia",
    notes: "React/Angular/Vue/Next.js; 0--15 yrs; 10 positions; graph database",
  },
  {
    title: "Junior Software Engineer",
    company: "Atos",
    location: "Istanbul (on-site)",
    url: "https://www.glassdoor.com/job-listing/junior-software-engineer-atos-JV_IC3361434_KO0,24.htm?jl=1010186601485",
    description:
      "Junior Software Engineer at Atos. Agile/Scrum methodology. Testing and debugging.",
    salary: null,
    experience: "Junior",
    visa: "Likely -- French multinational (100K+ employees)",
    type: "onsite",
    country: "Turkey",
    notes: "Agile/Scrum; testing & debugging; entry-level friendly",
  },
  {
    title: "Junior Software Development Engineer",
    company: "Amadeus IT",
    location: "Istanbul (on-site)",
    url: "https://www.glassdoor.com/job-listing/junior-software-development-engineer-amadeus-JV_IC3361434_KO0,36.htm?jl=1010223157545",
    description:
      "Junior Software Development Engineer at Amadeus IT. Travel tech company.",
    salary: null,
    experience: "Junior",
    visa: "Likely -- Spanish multinational (19K+ employees)",
    type: "onsite",
    country: "Turkey",
    notes: "Posted 3 days ago; design/code/test/debug; travel tech",
  },
  {
    title: "Software Engineer -- New Grad",
    company: "Good Job Games",
    location: "Istanbul (on-site)",
    url: "https://www.glassdoor.com/job-listing/software-engineer-new-grad-good-job-games-JV_IC3362919.htm?jl=1010126467196",
    description:
      "Software Engineer -- New Grad at Good Job Games. Go programming. Turkish gaming unicorn.",
    salary: null,
    experience: "New Grad",
    visa: "Unconfirmed -- Turkish gaming unicorn",
    type: "onsite",
    country: "Turkey",
    notes: "Go programming; 3.5B+ player reach; new grad specific",
  },
  {
    title: "Accelerator Program -- Software Engineer Web3",
    company: "Binance",
    location: "Istanbul (in-office or remote)",
    url: "https://builtin.com/jobs/mena/turkey/dev-engineering/search/software-engineer",
    description:
      "Software Engineer Web3 at Binance Accelerator Program. Java/Kafka/Spring/Web3 stack.",
    salary: null,
    experience: "Students / Recent Grads",
    visa: "Likely -- world's largest crypto exchange",
    type: "hybrid",
    country: "Turkey",
    notes: "Java/Kafka/Spring/Web3; students/recent grads; reposted 14h ago",
  },
  {
    title: "C++/Rust Graphics and Windowing System Software Engineer (Mir)",
    company: "Canonical",
    location: "Remote (Turkey eligible)",
    url: "https://builtin.com/jobs/mena/turkey/dev-engineering/search/software-engineer",
    description:
      "C++/Rust Graphics and Windowing System Software Engineer at Canonical. Junior level.",
    salary: "20K--200K USD/yr",
    experience: "Junior",
    visa: "N/A -- remote-first",
    type: "remote",
    country: "Turkey",
    notes: "C++/Rust/Flutter/OpenGL/Vulkan; junior level; 20K--200K USD/yr",
  },
  {
    title: "Software Engineer (Backend Game Developer)",
    company: "Spyke Games",
    location: "Istanbul (remote)",
    url: "https://builtin.com/jobs/mena/turkey/dev-engineering/search/software-engineer",
    description:
      "Backend Game Developer at Spyke Games. AWS/Java/MySQL/Postgres/Spring Boot stack.",
    salary: null,
    experience: "Junior",
    visa: "Unconfirmed -- Turkish gaming startup",
    type: "remote",
    country: "Turkey",
    notes: "AWS/Java/MySQL/Postgres/Spring Boot; junior level",
  },
  {
    title: "Software Engineer",
    company: "Bigger Games",
    location: "Istanbul (remote)",
    url: "https://builtin.com/jobs/mena/turkey/dev-engineering/search/software-engineer",
    description:
      "Software Engineer at Bigger Games. AWS/Java/Redis/Spring Boot stack. Scalable backend.",
    salary: null,
    experience: "Junior",
    visa: "Unconfirmed -- Turkish mobile gaming",
    type: "remote",
    country: "Turkey",
    notes: "AWS/Java/Redis/Spring Boot; junior level; scalable backend",
  },
  {
    title: "Associate Technical Architect (Rust + React + FastAPI)",
    company: "Tarento Group",
    location: "Delhi NCR (hybrid/onsite)",
    url: "https://www.foundit.in/job/associate-technical-architect-tarento-group-delhi-43933433",
    description:
      "Associate Technical Architect at Tarento Group. Axum/Tokio/Serde. Great Place to Work certified.",
    salary: null,
    experience: "0-1 years",
    visa: "Indian work auth.",
    type: "hybrid",
    country: "India",
    notes: "0--1 yrs; Axum/Tokio/Serde; Great Place to Work; Swedish HQ",
  },
  {
    title: "Rust Developer",
    company: "GoTrust",
    location: "Noida (onsite)",
    url: null,
    description:
      "Rust Developer at GoTrust. Rust/OS/systems/multithreading/Docker/Linux stack.",
    salary: null,
    experience: "1-2 years",
    visa: "Indian work auth.",
    type: "onsite",
    country: "India",
    notes:
      "1--2 yrs; Rust/OS/systems/multithreading/Docker/Linux; LinkedIn post by HR",
  },
  {
    title: "Reinforcement Learning Research Intern (Rust + C++)",
    company: "Arakoo",
    location: "Delhi/Gurgaon/Noida (onsite)",
    url: "https://internshala.com/internship/detail/reinforcement-learning-research-internship-in-multiple-locations-at-arakoo1785407276",
    description:
      "RL Research Intern at Arakoo. Chromium-based RL framework using C++, Rust, Java.",
    salary: "Rs 30--35K/mo",
    experience: "Intern (3 months)",
    visa: "Indian work auth.",
    type: "onsite",
    country: "India",
    notes:
      "3 months; Rs 30--35K/mo; Chromium-based RL framework; apply by Aug 29",
  },
  {
    title: "Rust Developer Intern (Backend)",
    company: "Qualyval",
    location: "WFH (UK-based company)",
    url: "https://internshala.com/internship/detail/work-from-home-rust-developer-internship-at-qualyval1785931168",
    description:
      "Rust Developer Intern at Qualyval. Backend systems using NodeJS or Rust. 6 months.",
    salary: "Rs 5--6K/mo",
    experience: "Intern (6 months)",
    visa: "Indian work auth. (remote)",
    type: "remote",
    country: "India",
    notes: "6 months; Rs 5--6K/mo; Node/Rust; REST APIs; apply by Sep 4",
  },
  {
    title: "Rust Developer (Freelancer -- RLHF Annotation)",
    company: "Deccan AI Experts",
    location: "Delhi (remote/freelance)",
    url: "https://www.foundit.in/job/rust-developer-freelancer-deccan-ai-experts-delhi-46455036",
    description:
      "Rust Developer (Freelancer) at Deccan AI Experts. Review/annotate Rust codebases.",
    salary: "Up to Rs 1500/hr",
    experience: "1-4 years",
    visa: "Indian work auth.",
    type: "remote",
    country: "India",
    notes:
      "1--4 yrs; up to Rs 1500/hr; review/annotate Rust codebases; IIT/IIM founders",
  },
  {
    title: "Frontend Developer (React / Next.js)",
    company: "PicEra Private Limited",
    location: "Delhi (in-office)",
    url: "https://www.shine.com/jobs/frontend-developer-react-nextjs/picera-private-limited/19170931",
    description:
      "Frontend Developer at PicEra. Build Album Viewer & Client Dashboard for photographers.",
    salary: "Rs 15--35K/mo",
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes: "Rs 15--35K/mo; React/Next.js/Tailwind/Redux/Zustand; 0--4 yrs",
  },
  {
    title: "React Developer",
    company: "iocombats (AppVersal)",
    location: "Noida",
    url: "https://www.shine.com/jobs/react-developer-in-noida/iocombats/19434960",
    description:
      "React Developer at AppVersal. Develop responsive web applications. Figma to pixel-perfect pages.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "React/Figma/REST; 0--4 yrs; app marketing 5M+ downloads; posted 3 days ago",
  },
  {
    title: "Frontend Developer",
    company: "Zero1 (Ozock)",
    location: "Delhi / Gurugram / Noida",
    url: "https://cutshort.io/job/Frontend-Developer-New-Delhi-Zero1-d4Aima4A",
    description:
      "Frontend Developer at Zero1. Work on in-house products, add new features, enhance UX.",
    salary: "Rs 3.5--5 LPA",
    experience: "0-2 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "Rs 3.5--5 LPA; 0--2 yrs; HTML5/CSS3/jQuery/Responsive; 100M+ visitors/mo",
  },
  {
    title: "Frontend Developer Intern",
    company: "CareFlick",
    location: "Noida (remote internship)",
    url: "https://www.shine.com/jobs/frontend-developer-noida-india/careflick/19164842",
    description:
      "Frontend Developer Intern at CareFlick. React.js and TypeScript. REST API integration.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "remote",
    country: "India",
    notes: "React/TypeScript/REST/Postman/Git; 3-month remote; AgeTech",
  },
  {
    title: "Frontend React JS Developer",
    company: "Dhwani Rural Information Systems",
    location: "Gurugram (onsite)",
    url: "https://www.shine.com/jobs/frontend-react-js-developer/dhwani-rural-information-systems/19189375",
    description:
      "Frontend React JS Developer at Dhwani. Ensure technical feasibility of frontend development.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes: "React/HTML5/CSS3/JS/SASS/LESS; social impact; 0--4 yrs",
  },
  {
    title: "Fresher Web Developer (React)",
    company: "Guidance Placement",
    location: "Noida / Delhi / Gurugram",
    url: "https://www.shine.com/jobs/fresher-job-web-design-java-react-php-developer-software-developer-urgent/guidance-placement/19394221",
    description:
      "Fresher Web Developer. Multiple developer profiles. 9 positions available.",
    salary: "Rs 1.5--3.5 LPA",
    experience: "0-1 year",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "Rs 1.5--3.5 LPA; 9 positions; placement agency; verify client company",
  },
  {
    title: "Fullstack Developer (.NET + React)",
    company: "Ahom Technologies",
    location: "Noida",
    url: "https://www.shine.com/jobs/fullstack-developerdotnet-react-noida/ahom-technologies/19195642",
    description:
      "Fullstack Developer at Ahom Technologies. .NET & React stack. CI/CD pipelines.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes: "React/.NET/Testing/CI-CD; 0--4 yrs",
  },
  {
    title: "React JS Developer",
    company: "Technoarch Softwares",
    location: "Noida",
    url: "https://www.shine.com/jobs/react-js-developer/technoarch-softwares/19227291",
    description:
      "React JS Developer at Technoarch. Consumer-facing web/app products. SEO principles.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes: "React/SASS/LESS/SEO/PostgreSQL; 0--4 yrs",
  },
  {
    title: "Full Stack Developer Intern",
    company: "Multiplier AI",
    location: "Noida (onsite)",
    url: "https://www.shine.com/jobs/full-stack-developer-intern/multiplier-ai/19461447",
    description:
      "Full Stack Developer Intern at Multiplier AI. AI-driven healthcare products.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "React/Node/Express/Mongo/Postgres/Tailwind/Python; posted 2 days ago",
  },
  {
    title: "Full Stack Developer Intern (React & Node)",
    company: "Interloop Private Limited",
    location: "Delhi (onsite)",
    url: "https://www.shine.com/jobs/full-stack-developer-intern-react-node-js/interloop-private-limited/19438053",
    description:
      "Full Stack Developer Intern at Interloop. 2-month internship. React and Node.js.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "React/Node/TypeScript/Mongo/Postgres/Tailwind; Zoho Partner; posted 5 days ago",
  },
  {
    title: "Full Stack Developer",
    company: "MantraCare",
    location: "Delhi (in-office)",
    url: "https://mantra.care/careers/full-stack-developer-delhi",
    description:
      "Full Stack Developer at MantraCare. ExpressJS, Node.js, React/NextJS, MongoDB, MySQL.",
    salary: "Rs 40--80K/mo",
    experience: "Fresher",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "Rs 40--80K/mo; React/Node/Express/Mongo/MySQL; healthcare 30+ countries",
  },
  {
    title: "Full Stack Developer (Node.js, NestJS, Angular)",
    company: "DigitalXNode",
    location: "Delhi NCR (remote for India)",
    url: "https://www.shine.com/jobs/full-stack-developer-nodejs-nestjs-angular/digitalxnode/19389705",
    description:
      "Full Stack Developer at DigitalXNode. Node/NestJS/TypeScript/Angular/MongoDB.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "remote",
    country: "India",
    notes: "Node/NestJS/TypeScript/Angular/MongoDB; 0--4 yrs; AI/NLP a plus",
  },
  {
    title: "Full Stack Developer (Node.js & React.js)",
    company: "Topcoder",
    location: "Noida",
    url: "https://www.shine.com/jobs/full-stack-developer-nodejs-reactjs/topcoder/19322486",
    description:
      "Full Stack Developer at Topcoder. Node/TS/React/Postgres/Mongo/AWS/Docker/K8s/Terraform.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "Node/TS/React/Postgres/Mongo/AWS/Docker/K8s/Terraform; global platform",
  },
  {
    title: "Full Stack Developer (Node JS & React/React Native)",
    company: "Gostravvy",
    location: "Noida (onsite)",
    url: "https://www.shine.com/jobs/full-stack-developer-node-js-and-react-native-react-js-noida/gostravvy/19412006",
    description:
      "Full Stack Developer at Gostravvy. Node (70%)/React (30%)/Mongo/AWS/WebSockets.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "Node (70%)/React (30%)/Mongo/AWS/WebSockets; travel tech; immediate joiners",
  },
  {
    title: "Full Stack Developer (Next.js + WordPress)",
    company: "Delhi Info Media Private",
    location: "Delhi NCR (onsite)",
    url: "https://www.shine.com/jobs/full-stack-developer-next-js-wordpress-headless-cms-delhi/delhi-info-media-private/19433856",
    description:
      "Full Stack Developer. Next.js + WordPress Headless CMS. SEO-friendly architecture.",
    salary: "Rs 10--25K/mo",
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "hybrid",
    country: "India",
    notes: "JS/React/Next.js/TS/Tailwind/WordPress/MySQL; 0--4 yrs",
  },
  {
    title: "Full Stack Developer (WordPress, Node.js, Next.js)",
    company: "Figmanet Solutions",
    location: "Noida (onsite)",
    url: "https://www.shine.com/jobs/full-stack-developer-wordpress-node-js-next-js/figmanet-solutions-private-limited/19430924",
    description:
      "Full Stack Developer at Figmanet. WordPress/JS/jQuery/PHP/Node/Next.js/Tailwind/React.",
    salary: "From Rs 25K/mo",
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes:
      "WordPress/JS/jQuery/PHP/Node/Next.js/Tailwind/React; from Rs 25K/mo",
  },
  {
    title: "Full Stack Developer",
    company: "BHARATIA",
    location: "Delhi (hybrid)",
    url: "https://internshala.com/job/detail/full-stack-developer-job-in-delhi-at-bharatia1785489081",
    description:
      "Full Stack Developer at BHARATIA. HTML5/CSS3/JS/Bootstrap/PHP/Node/React.",
    salary: "Rs 4--4.8 LPA",
    experience: "1 year",
    visa: "Indian local hire",
    type: "hybrid",
    country: "India",
    notes: "HTML5/CSS3/JS/Bootstrap/PHP/Node/React; Rs 4--4.8 LPA; hybrid",
  },
  {
    title: "Full Stack Developer",
    company: "Dexter Tech Labs",
    location: "Delhi NCR (onsite)",
    url: "https://www.shine.com/jobs/full-stack-developer-new-delhi-india/dexter-tech-labs/19241147",
    description:
      "Full Stack Developer at Dexter Tech Labs. React and Node.js. RESTful APIs.",
    salary: null,
    experience: "0-4 years",
    visa: "Indian local hire",
    type: "onsite",
    country: "India",
    notes: "React/Node/RESTful APIs; 0--4 yrs",
  },
  {
    title: "Engineer Trainee / Digital / Prime (via NQT)",
    company: "TCS",
    location: "PAN India (Delhi/NCR)",
    url: "https://nextstep.tcsapps.com/indiacampus/",
    description: "Engineer Trainee at TCS. Rs 3.36--12.26 LPA. Aug 2026 cycle.",
    salary: "Rs 3.36--12.26 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 3.36--12.26 LPA; Aug 2026 cycle; deadline ~Aug 13; 60% min",
  },
  {
    title: "Systems Engineer / Digital Specialist Engineer",
    company: "Infosys",
    location: "PAN India (Delhi/NCR)",
    url: "https://www.infosys.com/careers/apply.html",
    description:
      "Systems Engineer at Infosys. Rs 3.6--11 LPA. 2024/2025/2026 batches.",
    salary: "Rs 3.6--11 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 3.6--11 LPA; 2024/2025/2026 batches; 6.0 CGPA min",
  },
  {
    title: "Project Engineer / Turbo",
    company: "Wipro",
    location: "Noida / PAN India",
    url: "https://careers.wipro.com/",
    description:
      "Project Engineer at Wipro. Rs 3.5--8 LPA. NLTH drives run periodically.",
    salary: "Rs 3.5--8 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 3.5--8 LPA; NLTH drives run periodically",
  },
  {
    title: "Graduate Engineer Trainee",
    company: "HCL Technologies",
    location: "Noida HQ",
    url: "https://www.hcltech.com/careers",
    description:
      "Graduate Engineer Trainee at HCL Technologies. Rs 3.5--5 LPA.",
    salary: "Rs 3.5--5 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 3.5--5 LPA; multiple cycles through 2026",
  },
  {
    title: "Software Engineer (GenC / GenC Next)",
    company: "Cognizant",
    location: "Noida / Gurgaon",
    url: "https://www.cognizant.com/in/en/careers",
    description:
      "Software Engineer at Cognizant. Rs 4--7 LPA. 2024/2025/2026 batches.",
    salary: "Rs 4--7 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 4--7 LPA; 2024/2025/2026 batches; 60% min",
  },
  {
    title: "Software Engineer (Exceller Program)",
    company: "Capgemini",
    location: "Noida / PAN India",
    url: "https://www.capgemini.com/in-en/careers/join-capgemini/job-search/",
    description:
      "Software Engineer at Capgemini. Rs 4--7.5 LPA. 2025/2026 batches.",
    salary: "Rs 4--7.5 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 4--7.5 LPA; 2025/2026 batches",
  },
  {
    title: "Software Development Engineer I (SDE-1)",
    company: "Amazon",
    location: "Delhi / Noida",
    url: "https://jobs.amazon.in/app",
    description:
      "SDE-1 at Amazon. Rs 30+ LPA. Java/C++/Python. Strong DSA needed.",
    salary: "Rs 30+ LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 30+ LPA; Java/C++/Python; strong DSA needed; rolling",
  },
  {
    title: "Software Engineer (Entry Level)",
    company: "Microsoft",
    location: "Noida",
    url: "https://careers.microsoft.com/india",
    description:
      "Software Engineer at Microsoft. Rs 15--25 LPA. Hybrid 3 days office.",
    salary: "Rs 15--25 LPA",
    experience: "Entry Level",
    visa: "Indian national",
    type: "hybrid",
    country: "India",
    notes: "Rs 15--25 LPA; hybrid 3 days office; 2024/2025 batches",
  },
  {
    title: "Software Engineer",
    company: "Samsung R&D Institute India",
    location: "Noida (Sector 135)",
    url: "https://research.samsung.com/careers",
    description:
      "Software Engineer at Samsung R&D. Rs 18--24 LPA. B.Tech CS/IT/ECE.",
    salary: "Rs 18--24 LPA",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "Rs 18--24 LPA; B.Tech CS/IT/ECE; 60%+ CGPA",
  },
  {
    title: "Software Engineer Trainee",
    company: "Newgen Software",
    location: "Noida",
    url: "https://omnirecruit.newgen.co.in/",
    description:
      "Software Engineer Trainee at Newgen. Rs 4.25 LPA after training.",
    salary: "Rs 4.25 LPA after training",
    experience: "Fresh Graduate",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes:
      "Rs 4.25 LPA after training; Rs 20K/mo stipend during; low-code platform",
  },
  {
    title: "Software Developer 2",
    company: "Oracle",
    location: "Noida / Delhi",
    url: "https://careers.oracle.com/",
    description:
      "Software Developer 2 at Oracle. Python/Java/Angular/SQL. IC2 level.",
    salary: null,
    experience: "0-1 years",
    visa: "Indian national",
    type: "onsite",
    country: "India",
    notes: "0--1 yrs; Python/Java/Angular/SQL; IC2 level",
  },
];

writeFileSync("data/imported-jobs.json", JSON.stringify(jobs, null, 2));
console.log(`Wrote ${jobs.length} jobs to data/imported-jobs.json`);
